In [2]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

In [13]:
A = list(range(1,10))

In [14]:
B = np.arange(1, 10)

In [15]:
A

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

list:    物體  
array:   向量

In [17]:
A * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
B * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
B.cumsum()
#連加

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [21]:
B.cumprod()
#連乘

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [22]:
N = B.reshape(3, 3)

In [27]:
N

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
N.mean()

5.0

In [25]:
N.mean(axis = 0)
#0=直的 行

array([4., 5., 6.])

In [26]:
N.mean(axis = 1)
#0=橫的 列

array([2., 5., 8.])

In [30]:
np.random.seed(1)
#選一個模式，只有有效一次，要重新設

In [32]:
np.random.randint(10)

5

In [33]:
np.random.randint(10)

8

In [35]:
np.random.randn()
#平均0 標準差1 常態分配 

-1.0729686221561705

In [38]:
np.random.randn(3, 3)
#array

array([[-1.33195167, -1.76068856, -1.65072127],
       [-0.89055558, -1.1191154 ,  1.9560789 ],
       [-0.3264995 , -1.34267579,  1.11438298]])

In [39]:
S = ["a", "b", "c", "d"]

In [40]:
np.random.choice(S)

'd'

In [41]:
np.random.choice(S, 2)

array(['d', 'd'], dtype='<U1')

In [42]:
np.random.choice(S, 8)
#可以重複取

array(['d', 'd', 'a', 'c', 'd', 'b', 'c', 'c'], dtype='<U1')

In [47]:
np.random.choice(S, 4, replace = False)
#不重複取

array(['c', 'b', 'a', 'd'], dtype='<U1')

In [48]:
np.random.choice(S, size = (3, 3))

array([['a', 'c', 'c'],
       ['c', 'b', 'c'],
       ['c', 'd', 'b']], dtype='<U1')

In [49]:
P = [0.8, 0.2, 0, 0]

In [51]:
np.random.choice(S, 4, p = P)
#可以設機率

array(['a', 'a', 'b', 'a'], dtype='<U1')