In [9]:
import numpy as np
list = [5] * 5
array = np.array(list) * 1.1
print(list)
print(array)

[5, 5, 5, 5, 5]
[5.5 5.5 5.5 5.5 5.5]


python 先列後行

In [13]:
grades = np.array([[85, 70, 80],
                 [12, 88, 77],
                 [85, 91, 33]])
weights = np.array([0.2, 0.35, 0.45])

In [17]:
wgrades = grades * weights

In [18]:
wgrades

array([[17.  , 24.5 , 36.  ],
       [ 2.4 , 30.8 , 34.65],
       [17.  , 31.85, 14.85]])

In [15]:
wgrades.sum(axis = 0)

array([36.4 , 87.15, 85.5 ])

In [16]:
wgrades.sum(axis = 1)

array([77.5 , 67.85, 63.7 ])

In [12]:
def ARGV(*argv):
    for i in argv:
        print(i)
        print(type(argv))

In [13]:
ARGV("Hello", "World")

Hello
<class 'tuple'>
World
<class 'tuple'>


In [14]:
def square(x):
    return x**2

In [16]:
print(map(square, [1,2,3,4,5])